name: Snapshot Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node with 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn global add lerna
      run: |
        yarn global add lerna
    - name: yarn install and run snapshot test
      run: |
        yarn install
        yarn run test:snapshot
